# Generated by Django 3.2.9 on 2022-11-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('artist', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('genre', models.CharField(choices=[('R', 'Рок'), ('E', 'Электроника'), ('P', 'Поп'), ('C', 'Классика'), ('O', 'Саундтреки')], max_length=1)),
            ],
        ),
    ]
